// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using parcial_1;

namespace parcial_1.Migrations
{
    [DbContext(typeof(TareasDbContext))]
    partial class TareasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("parcial_1.Detalles", b =>
                {
                    b.Property<int>("IdDetalles")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id Detalles")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("Fecha")
                        .HasColumnType("DateTime");

                    b.Property<int>("IdRecursos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTareas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecursoIdRecursos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TareaIdTareas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tiempo")
                        .HasColumnName("Tiempo")
                        .HasColumnType("int");

                    b.HasKey("IdDetalles");

                    b.HasIndex("RecursoIdRecursos");

                    b.HasIndex("TareaIdTareas");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("parcial_1.Recursos", b =>
                {
                    b.Property<int>("IdRecursos")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID Recurso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRecursos");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Nombre");
                });

            modelBuilder.Entity("parcial_1.Tareas", b =>
                {
                    b.Property<int>("IdTareas")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID Tarea")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnName("Estado")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Estimacion")
                        .HasColumnName("Estimacion")
                        .HasColumnType("int");

                    b.Property<int>("IdRecursos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponsableIdRecursos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("Titulo")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnName("Vencimiento")
                        .HasColumnType("DateTime");

                    b.HasKey("IdTareas");

                    b.HasIndex("ResponsableIdRecursos");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("parcial_1.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID Usuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnName("Clave")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnName("Usuario")
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("parcial_1.Detalles", b =>
                {
                    b.HasOne("parcial_1.Recursos", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoIdRecursos");

                    b.HasOne("parcial_1.Tareas", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaIdTareas");
                });

            modelBuilder.Entity("parcial_1.Recursos", b =>
                {
                    b.HasOne("parcial_1.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("parcial_1.Tareas", b =>
                {
                    b.HasOne("parcial_1.Recursos", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableIdRecursos");
                });
#pragma warning restore 612, 618
        }
    }
}
